feat: sdk 1008 manual session
rudderlabs/rudder-sdk-android pull request #404
Opened 2024-03-11 07:40 UTC by itsdebs

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] Version upgraded (project, README, gradle, podspec etc)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2024-04-29 19:03 UTC, ChryssaAliferi requested changes
Great effort with the analytics test and `TestAnalytics` provider!! But lets not create more `generateTestAnalytics` methods.
In this patch file I have refactored both `generateTestAnalytics` methods to one, the `fun provideAnalytics(...)`:
[feat__refactors_provideAnalytics_test_provider.patch](https://github.com/rudderlabs/rudder-sdk-android/files/15153656/feat__refactors_provideAnalytics_test_provider.patch)


Take a look and let me know! This is way more organised and adjustable on all test/business logic cases.

Also I need us to merge the branch with the current `feat/android` because there are conflicts that make me unsure on what to review. When we do this I will try to review once more!

2024-05-01 22:51 UTC, ChryssaAliferi commented on android/src/main/java/com/rudderstack/android/utilities/SessionUtils.kt
> +private fun Analytics.updateSessionLastActiveTimestamp() {
You can simplify and use directly the userSessionsState value, like that:

```
private fun Analytics.updateSessionLastActiveTimestamp() {
    userSessionState?.value?.let {
        it.copy(lastActiveTimestamp = defaultLastActiveTimestamp)
    }
}
```

2024-05-01 22:51 UTC, ChryssaAliferi commented on core/src/main/java/com/rudderstack/core/internal/ConfigDownloadServiceImpl.kt
> +    webService: WebService? = null
`private val webService: WebService? = null`

2024-05-01 22:51 UTC, ChryssaAliferi commented on samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
> +                copy(
Please would you like to explain more about this `copy` method and that callback added here? Frankly, it does not look much user-friendly.

2024-05-02 09:57 UTC, itsdebs commented on core/src/test/java/com/rudderstack/core/internal/plugins/EventSizeFilterPluginTest.kt
> +    val mockkRule = MockKRule(this)
This came up due to merging, EventSizeFiltering is a separate feature and was implemented in an old PR
[pull-request](https://github.com/rudderlabs/rudder-sdk-android/pull/396)

2024-05-08 13:27 UTC, itsdebs commented on core/src/test/java/com/rudderstack/core/internal/plugins/EventSizeFilterPluginTest.kt
> +    val mockkRule = MockKRule(this)
We can remove these in separate PR

2024-05-08 13:28 UTC, itsdebs commented on core/src/main/java/com/rudderstack/core/internal/plugins/EventSizeFilterPlugin.kt
> +    private var _analyticsRef = WeakReference<Analytics>(null)
I have not been through this plugin, this plugin was part of the event filtering task, can we deal with it in a separate PR? 
You can create a linear ticket for improvements.

2024-06-25 15:37 UTC, 1abhishekpandey requested changes

2024-06-25 15:37 UTC, 1abhishekpandey commented on samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
> +            }
Can you please revert this change for now?

I tried to disable the `lifecycle` flag to `false` and after that also I can see the lifecycle events in our dashboard.

2025-02-12 12:40 UTC, ChryssaAliferi commented
Closing this PR as all the progress has been included in the new [Kotlin SDK](https://github.com/rudderlabs/rudder-sdk-kotlin).

2025-02-12 12:40 UTC, closed without merging