Added Getter Method for Group ID
rudderlabs/rudder-sdk-android pull request #51
Opened 2020-11-23 12:20 UTC by desusai7

## Description of the change

> Added Getter Method for GroupId in RudderMessage Class 

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2020-11-23 12:23 UTC, ruchiramoitra approved these changes

2020-11-23 12:26 UTC, arnab-p requested changes

2020-11-23 12:26 UTC, arnab-p commented on core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
> +        return groupId;
```suggestion
        return this.groupId;
```

2020-11-23 12:29 UTC, desusai7 commented on core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
> +        return groupId;
Yeah will change that

2020-11-24 00:00 UTC, arnab-p approved these changes

2020-12-07 10:22 UTC, merged